In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
data = pd.read_excel("canada_per_capita_income.xlsx")

In [3]:
data

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000
5  4100      6.0    8  810000

In [5]:
import math 
data.bedroom.median()

4.0

In [7]:
data.bedroom = data.bedroom.fillna(data.bedroom.median())
data

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      4.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000
5  4100      6.0    8  810000

In [11]:
model = linear_model.LinearRegression()
model.fit(data.drop('price',axis='columns'),data.price)

LinearRegression()

In [14]:
model.predict([[3000,3,40]])

array([498408.25158031])

In [15]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [16]:
model.intercept_

221323.0018654039

In [17]:
model.predict([[2500,4,15]])

array([546558.858403])

In [18]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [19]:
model.intercept_

221323.0018654039

In [21]:
112.06244194*2500+23388.88007794*4-3231.71790863*15+221323.0018654039

546558.8583977139